name: Continuous Integration

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [18.x, 20.x]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'yarn'
        
    - name: Install dependencies
      run: yarn install --frozen-lockfile
      
    - name: Run linting
      run: yarn lint
      
    - name: Run type checking
      run: yarn type-check
      
    - name: Run tests
      run: yarn test --coverage
      
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage/lcov.info
        flags: unittests
        name: codecov-umbrella
        fail_ci_if_error: false

  build:
    runs-on: ubuntu-latest
    needs: test
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Use Node.js 20.x
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        cache: 'yarn'
        
    - name: Install dependencies
      run: yarn install --frozen-lockfile
      
    - name: Build client
      run: |
        cd client
        yarn build
        
    - name: Build API
      run: |
        cd api
        yarn build

  # Temporarily disabled due to CodeQL permission issues
  # Will re-enable after critical TypeScript fixes are deployed
  # security:
  #   runs-on: ubuntu-latest
  #   
  #   steps:
  #   - name: Checkout code
  #     uses: actions/checkout@v4
  #     
  #   - name: Run security audit
  #     run: |
  #       yarn audit --level moderate
  #       cd client && yarn audit --level moderate
  #       cd ../api && yarn audit --level moderate
  #     continue-on-error: true
  #     
  #   - name: Run CodeQL Analysis
  #     uses: github/codeql-action/init@v2
  #     with:
  #       languages: javascript, typescript
  #       
  #   - name: Perform CodeQL Analysis
  #     uses: github/codeql-action/analyze@v2

  docker:
    runs-on: ubuntu-latest
    needs: [test, build]  # Removed 'security' dependency
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      
    - name: Test Docker build
      run: |
        docker-compose -f docker-compose.yml build --no-cache
        
    - name: Test Docker services
      run: |
        docker-compose -f docker-compose.yml up -d
        sleep 30
        docker-compose -f docker-compose.yml ps
        docker-compose -f docker-compose.yml down

  conventional-commits:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        
    - name: Check conventional commits
      uses: wagoid/commitlint-github-action@v5
      with:
        configFile: .commitlintrc.js 